--Simply add the item and the number you want to list and you shall receive :)

ITEMS_I_WANT = {
	{"roboport", 25},
	{"logistic-robot", 300},
	{"construction-robot", 100},
	{"logistic-chest-active-provider", 50},
	{"logistic-chest-buffer", 50},
	{"logistic-chest-passive-provider", 200},
	{"logistic-chest-requester", 100},
	{"logistic-chest-storage", 100},

	{"solar-panel", 250},
	{"accumulator", 200},
	{"medium-electric-pole", 200},
	{"big-electric-pole", 50},

	{"red-wire", 50},
	{"constant-combinator", 50},
	{"decider-combinator", 50},
	{"power-switch", 50},

	{"personal-roboport-mk2-equipment", 5},
	{"fusion-reactor-equipment", 5},
	{"destroyer-capsule", 50},
	{"power-armor-mk2", 1},
	{"energy-shield-mk2-equipment", 1},
	{"personal-laser-defense-equipment", 1},
	{"exoskeleton-equipment", 5},
	{"steel-axe", 5},

	{"lab", 10},
	{"science-pack-1", 50},
	{"assembling-machine-3", 50},
	{"electric-mining-drill", 50},
	{"electric-furnace", 50},
	{"express-underground-belt", 100},
	{"express-transport-belt", 300},
	{"stack-filter-inserter", 50},
	{"long-handed-inserter", 50},
	{"fast-inserter", 50},

	{"hacked-express-splitter", 100},	
	{"electric-steel-furnace", 50},
	{"factory-1", 4},
	{"factory-2", 3},
	{"factory-3", 3},
	{"farl", 5},

	{"centrifuge", 1},
	{"uranium-235", 200},
	{"kovarex-enrichment-process", 1},
	{"nuclear-reactor ", 4},
	{"heat-exchanger", 50},
	{"heat-pipe", 200},
	{"steam-turbine", 100},
	{"uranium-fuel-cell", 100},

	{"pipe", 100},
	{"steam-engine", 50},
	{"boiler", 25},
	{"offshore-pump", 5},
	{"pipe-to-ground", 50},
	{"storage-tank", 10},
}